### ISSUE TITLE
<WRMHEADER xmlns="http://schemas.microsoft.com/DRM/2007/03/PlayReadyHeader" version="4.0.0.0"> <DATA>       <PROTECTINFO>         <ALGID>AESCTR</ALGID>         <KEYLEN>16</KEYLEN>       </PROTECTINFO>       <LA_URL> URL for license acquisition </LA_URL>       <LUI_URL>         URL for Non-silent license acquisition web page       </LUI_URL>     <DS_ID>base64-encoded guid</DS_ID>     <KID>base64-encoded kid</KID>     <CUSTOMATTRIBUTES xmlns="">       <mm:Publisher xmlns:mm="urn:schema-musicmogul-com">            <mm:Author>                 Elvis Presley            </mm:Author>            <mm:CreationDate>                 2007/08/21:12:00:00            </mm:CreationDate>         </mm:Publisher>     </CUSTOMATTRIBUTES>     <CHECKSUM>       checksum of the content key for verification     </CHECKSUM>   </DATA> </WRMHEADER>

### ISSUE THREAD

**Issue by streamfitness** [MicrosoftDocs/PlayReady#101]
[Enter feedback here]

---
#### Document Details
[AUTHOR/DEVELOPED BY: JOSEPH S. FABIAN JR  2020-2021] [
[109c673c1b909bcd80ab5a2ed2f98672.pdf](https://github.com/MicrosoftDocs/PlayReady/files/6462561/109c673c1b909bcd80ab5a2ed2f98672.pdf)
https://www.fit@virt.entertainment.com// FITNESS-1VIRTUAL//Streamfitness@outlook.com]
⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94dcc0f3-fc01-7bb1-2bad-9f761b0064d1
* Version Independent ID: f3a9f462-f9b1-5456-d6de-632ddd3d46ea
* Content: [PlayReady Header Specification - PlayReady](https://docs.microsoft.com/en-us/playready/specifications/playready-header-specification)
* Content Source: [Docs/Specifications/playready-header-specification.md](https://github.com/MicrosoftDocs/PlayReady/blob/live/Docs/Specifications/playready-header-specification.md)
* Product: **playready**
* Technology: **drm**
* GitHub Login: @mimisasouvanh
* Microsoft Alias: **windowsdriverdev**

**Comment by mimisasouvanh** [comment]
@isharma-msft @swenkeratmicrosoft FYI

**Comment by swenkeratmicrosoft** [comment]
@streamfitness 

This issue appears to have a title with a partially-filled WRMHeader and no additional information.

Could you please explain the question or problem you have in detail?

Thanks,
-Sam Wenker with the Microsoft PlayReady team

**Comment by swenkeratmicrosoft** [comment]
Since no additional information regarding the actual issue has been customer-provided in nearly 3 weeks. I am closing this issue.

Thanks,
-Sam Wenker with the Microsoft PlayReady team
