### ISSUE TITLE
How can I check the PlayEeady version on my pc?

### ISSUE THREAD

**Issue by MyStoryG** [MicrosoftDocs/PlayReady#102]
In Windows 10 20h2, decoding is performed when 8 or 16 bytes of Initialization Vector is set. However, in version 1909, decoding is only possible if the initialization vector is set to 8 bytes. This seems to be a problem with the PlayReady version. How can I check the version of PlayReady currently set up to my PC? In PlayReady versions 3.3 and earlier, only 64-bit IVs (8-byte IVs) are supported in CTR mode. Starting with PlayReady version 4.0, both 64-bit and 128-bit IVs (8-byte and 16-byte IVs) are supported both in CTR and CBC modes.

**Comment by swenkeratmicrosoft** [comment]
In a UWP application, you can use the following API.

https://docs.microsoft.com/en-us/uwp/api/windows.media.protection.protectioncapabilities.istypesupported

Use "com.microsoft.playready.recommendation" for the key system string (or "com.microsoft.playready.recommendation.3000" if you intend to use SL3000 hardware DRM).

In your "type" parameter, first specify your codec information as documented above.

For 16-byte IV support, you can add the following feature to your query.
encryption-iv-size=16

For CBCS content support, you can add the following feature to your query.
encryption-type=cbcs

When using EME in a webpage in Microsoft Edge, you can use the MSMediaKeys.isTypeSupportedWithFeatures API to achieve the same effect - the parameters and result are the same.

We are aware that these two features are currently undocumented at the link above and are working with the appropriate team to update the documentation.

I hope that helps.  If not, please reopen the issue with any additional questions you have.

-Sam Wenker with the Microsoft PlayReady team
