### ISSUE TITLE
"com.microsoft.playready.recommendation" documentation

### ISSUE THREAD

**Issue by markriley9999** [MicrosoftDocs/PlayReady#107]
There seems to be a great deal of confusion (well i'm confused anyway!) around the use of the 'com.microsoft.playready.recommendation' vs the (legacy?) 'com.microsoft.playready' keysystem.

based on the recommendation from @swenkeratmicrosoft it would appear that we should now be using 'com.microsoft.playready.recommendation' - but i can't find where this is documented (and i'm not even sure if it applies to all browsers or just the MS Edge browser), see:
https://github.com/Dash-Industry-Forum/dash.js/issues/2658#issuecomment-405690840

i'm working with embedded TV browsers, eg WebOs, Vewd etc - and i'm working on the assumption that they also need to support the 'com.microsoft.playready.recommendation' - is that correct?

**Comment by swenkeratmicrosoft** [comment]
com.microsoft.playready.recommendation is specific to _Windows_.

On Windows, I am unaware of any browser that supports PlayReady except Edge.  If they do, it's up to them what key systems they support and how they support them, e.g. they could decide to implement com.microsoft.playready such that it remaps to com.microsoft.playready.recommendation before it calls into the OS, or might use com.microsoft.playready.recommendation only and not support com.microsoft.playready at all, or whatever they wish to do.  Microsoft has no control over that.

Similarly, Microsoft has no control over what third-party browsers use for their key system string.

Hope that helps,

-Sam Wenker with the Microsoft PlayReady team

**Comment by sergiofagostinho** [comment]
hi @markriley9999 , I'd suggest taking a look at https://github.com/google/shaka-player/issues/1495, as it documents the process that the Shaka Player community took to support `com.microsoft.playready.recommendation`.

**Comment by swenkeratmicrosoft** [comment]
Resolved in #122.  New page under "Overview" is expected to go live by end of December.
