### ISSUE TITLE
Individualization details

### ISSUE THREAD

**Issue by sergiofagostinho** [MicrosoftDocs/PlayReady#29]
Information in this page is very generic. Would be interesting to have more detail about IBX (Individualization Black Box), ClientIDs, and license persistence.
William Zhang's blog has [an interesting post on this](https://blogs.msdn.microsoft.com/playready4/2011/10/10/ways-to-unqiuely-identify-a-silverlight-client/), but seems limited to Silverlight and might be out of date on some regards.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 602057bf-ed78-288c-56c7-0bd23b4a0b40
* Version Independent ID: ef4acac8-1add-6268-925b-be6dcd848e6a
* Content: [PlayReady Individualization - PlayReady](https://docs.microsoft.com/en-us/playready/overview/individualization)
* Content Source: [Docs/Overview/individualization.md](https://github.com/MicrosoftDocs/PlayReady/blob/live/Docs/Overview/individualization.md)
* Service: **playready**
* GitHub Login: @RolandLeFranc
* Microsoft Alias: **rolefran**

**Comment by RolandLeFranc** [comment]
Thanks for the feedback.
We've addressed the issues you raised in the next update to be published next week.
