### ISSUE TITLE
Secure Clock Status Site

### ISSUE THREAD

**Issue by jkbreuer** [MicrosoftDocs/PlayReady#33]
Can a Secure Clock Status site be made available to facilitate operations between Microsoft and partners?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7785dc36-8416-ec1f-04fb-e85084ec5796
* Version Independent ID: bc60b6ff-6cb2-d036-b9d5-2f740f6db190
* Content: [PlayReady Secure Clock Services for PlayReady Clients - PlayReady](https://docs.microsoft.com/en-us/playready/overview/secure-clock-services)
* Content Source: [Docs/Overview/secure-clock-services.md](https://github.com/MicrosoftDocs/PlayReady/blob/live/Docs/Overview/secure-clock-services.md)
* Product: **playready**
* GitHub Login: @RolandLeFranc
* Microsoft Alias: **rolefran**

**Comment by RolandLeFranc** [comment]
Yes, we're working on it, and it will be released at the end of the summer.

**Comment by mimisasouvanh** [comment]
@jkbreuer Good question. AFAIK it was delayed. I will ask the team and give you a reply soon. Thanks!

**Comment by mimisasouvanh** [comment]
@jkbreuer Hi Joseph, the rollout is planned for the end of this November.
