### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by vijayanandmit** [MicrosoftDocs/PlayReady#38]
[Enter feedback here]
Spelling error in section 3.3. v4.3.0.0
Change particulat to particular 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94dcc0f3-fc01-7bb1-2bad-9f761b0064d1
* Version Independent ID: f3a9f462-f9b1-5456-d6de-632ddd3d46ea
* Content: [PlayReady Header Specification - PlayReady](https://docs.microsoft.com/en-us/playready/specifications/playready-header-specification)
* Content Source: [Docs/Specifications/playready-header-specification.md](https://github.com/MicrosoftDocs/PlayReady/blob/live/Docs/Specifications/playready-header-specification.md)
* Product: **playready**
* GitHub Login: @RolandLeFranc
* Microsoft Alias: **rolefran**

**Comment by mimisasouvanh** [comment]
Thanks for catching this! I fixed the error, and it should be live soon.
