### ISSUE TITLE
Revocation list documentation - suggestions

### ISSUE THREAD

**Issue by sebasmonia** [MicrosoftDocs/PlayReady#44]
I couldn't find in the docs any information on how the revocation list update works in the server.

Is the revocation list updated via a FileWatcher? In that case I can point it to "revo.xml" in the configuration and then update that file weekly. 
Or does it require a server restart, which will happen when the web.config is modified to point to a new file?

**Comment by mimisasouvanh** [comment]
Closed due to issue being open for > 6 months. Currently, IIS needs to be restarted in order to pick up changes in the new revocation data file. The team will pick this up as a suggestion and will consider it in the future.
