### ISSUE TITLE
How to get PlayReady Server SDK

### ISSUE THREAD

**Issue by sukhdev22** [MicrosoftDocs/PlayReady#45]
I am searching fro PlayReady Server SDK for 5 hours, since morning....But I could not find where the hell to download it from??????????????????????????????????????????????

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62199734-46db-9461-b84b-dee918bec7e4
* Version Independent ID: df19be56-228d-039e-4f75-86e70aa0c1d3
* Content: [PlayReady Server SDK - PlayReady](https://docs.microsoft.com/en-us/playready/overview/server-sdk)
* Content Source: [Docs/Overview/server-sdk.md](https://github.com/MicrosoftDocs/PlayReady/blob/live/Docs/Overview/server-sdk.md)
* Product: **playready**
* GitHub Login: @mimisasouvanh
* Microsoft Alias: **windowsdriverdev**

**Comment by mimisasouvanh** [comment]
@sukhdev22 I'm sorry for this experience. You must sign up for a License to install the PlayReady Server SDK at https://www.microsoft.com/playready/licensing/getplayready/
