### ISSUE TITLE
Packaging content for .mp4 DASH with key rotation but without embedded license

### ISSUE THREAD

**Issue by srebrnyp** [MicrosoftDocs/PlayReady#46]
Dear, 

I was unable to find information about how to package content in .mp4 DASH with key rotation. Though, there is a paragraph about "Packaging Content" > "MP4-based Formats Supported by PlayReady Clients" with "DASH rotating keys", it provides only information about how to package content when using embedded license.

I am interested in the case without embedded license, i.e., when a media player fetches a new license from the license server for each movie fragment. DASH specifies that a key ID encrypting a movie fragment should be put in the moof -> traf -> sgpd of type seig box. Key should be available to the player at the moment when the fragment is about to be played. 

Could you provide description of how DASH manifest should look like and what should PlayReady Object contain. Should there be any PSSH box in the moov box present? 

Best regards

**Comment by mimisasouvanh** [comment]
Closed due to issue being open for > 6 months.
