### ISSUE TITLE
No XML schema published

### ISSUE THREAD

**Issue by thomaswm2014** [MicrosoftDocs/PlayReady#48]
I did not find official XML schema (XSD) for the namespace "urn:microsoft:playready".
I think this should be added to the specification.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bce8cc0-d81b-ffed-6a30-62be6050a098
* Version Independent ID: 0ead46d0-189e-e0f9-619e-b0cc1419e705
* Content: [DASH Content Protection using Microsoft PlayReady - PlayReady](https://docs.microsoft.com/en-us/playready/specifications/mpeg-dash-playready#feedback)
* Content Source: [Docs/Specifications/mpeg-dash-playready.md](https://github.com/MicrosoftDocs/PlayReady/blob/live/Docs/Specifications/mpeg-dash-playready.md)
* Product: **playready**
* Technology: **drm**
* GitHub Login: @mimisasouvanh
* Microsoft Alias: **windowsdriverdev**

**Comment by swenkeratmicrosoft** [comment]
PlayReady XML is not intended to be built or parsed outside the PlayReady client/server code, and the XML scheme (XSD) is thus internal.  If you think publishing it is worthwhile, could you explain what information you hope to glean from it in detail?

Thanks,
-Sam Wenker with the Microsoft PlayReady team

**Comment by ProIcons** [comment]
Parsing and Validating MPDs

**Comment by swenkeratmicrosoft** [comment]
Ah, so you're specifically referring to the PlayReady Header XML which begins with the WRMHEADER tag?

If so, is the following sufficient?

https://docs.microsoft.com/en-us/playready/specifications/playready-header-specification

Thanks,
-Sam Wenker with the Microsoft PlayReady team

**Comment by ProIcons** [comment]
I don't know about the other guy, but for me is good enough thanks.

**Comment by thomaswm2014** [comment]
I wanted to have an official XML schema to be able to validate my code which generated the XML part (along the other parts) while doing encryption. (We did not use code from MS to do that)
Obviously the referred documentation was enough to make the implementation but as it is a human readable description of the XML it cannot be used for automated validation.
I did not make a schema myself as having the implementation and validation from the same source can hide issues.

Since then (2019) we abandoned PlayReady and kept Fairplay and Widevine only.

**Comment by ProIcons** [comment]
Right so i might have responded fast on this one.
This is the only piece of information i have on Dash Manifests
regarding Playready content protection
```xml
<xs:schema targetNamespace="urn:microsoft:playready"
           attributeFormDefault="qualified"
           elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="urn:microsoft:playready">
    <xs:element name="pro" type="xs:base64Binary"/>
</xs:schema>
```
I don't know what "pro" attribute is and what it should contain
besides that it is a base64binary.

**Comment by thomaswm2014** [comment]
The 'pro' attribute contains the PlayReadObject base64 encoded version. (which is also part of the PSSH box)
https://docs.microsoft.com/en-us/playready/specifications/playready-header-specification#2-playready-object-pro

as it is described here:
https://docs.microsoft.com/en-us/playready/specifications/mpeg-dash-playready#21-dash-contentprotection-descriptor-elements

"
In the case of PlayReady, a PlayReady Object (PRO) [PRO] can be contained in a cenc:pssh element, an mspr:pro element, or a ‘pssh’ box to enable license acquisition. **The mspr:pro element is defined by Microsoft PlayReady, and includes only the PRO [PRO] information**, not the box structure included in ‘pssh’ and cenc:pssh. Including both mspr:pro and cenc:pssh will enable old players including a player based on Silverlight, and new players including web pages using script to play protected DASH presentations on HTML5 browsers.
"

**Comment by ProIcons** [comment]
That's all fine, however shouldn't be an xsd schema to be able to validate PlayReadObject ?

**Comment by swenkeratmicrosoft** [comment]
By definition, an XSD can only validate XML-formatted data.  Since a PlayReadyObject is *binary*, an XSD for it is meaningless.

-Sam Wenker with the Microsoft PlayReady team
