### ISSUE TITLE
licenses response sample in case of non-persistent and persistent licenses

### ISSUE THREAD

**Issue by Goltaevo** [MicrosoftDocs/PlayReady#49]
Hello,

it would be usefull to have license response samples in case of non-persistent and persistent licenses somewhere here )

BR, Evgeny

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f80f528c-c782-ba4b-215a-807f1b1a3dc8
* Version Independent ID: 74d5f9ad-87dd-203f-5de9-151066a3a38c
* Content: [Persistent and Non-persistent Licenses - PlayReady](https://docs.microsoft.com/en-us/playready/overview/license-persistence#feedback)
* Content Source: [Docs/Overview/license-persistence.md](https://github.com/MicrosoftDocs/PlayReady/blob/live/Docs/Overview/license-persistence.md)
* Product: **playready**
* Technology: **drm**
* GitHub Login: @mimisasouvanh
* Microsoft Alias: **windowsdriverdev**

**Comment by swenkeratmicrosoft** [comment]
A PlayReady license response:
1. Cannot be processed by any client other than the one that issued it.
2. Looks identical for the non-persistent/persistent license cases excluding the licenses themselves.
3. Includes the licenses only in base64-encoded raw-binary form which is not human readable.

As such, I'd be curious as to the value of including the requested sample.  What information are you trying to obtain from it?

Thanks,
-Sam Wenker with the Microsoft PlayReady team
