### ISSUE TITLE
EME spec reference

### ISSUE THREAD

**Issue by timwright314159** [MicrosoftDocs/PlayReady#50]
Even more useful than saying Secure Delete meet a requirement in EME is to give the section in EME where that requirement is.  I can't find such a requirement in the EME spec though there are requirements to allow users to delete persistent identifiers - is that the requirement in question? Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5a872f1-fb3a-4c76-af89-e4d8aa7303a1
* Version Independent ID: e0a830fc-bd15-4a70-8458-dcaf3c3aed48
* Content: [PlayReady Secure Delete Server - PlayReady](https://docs.microsoft.com/en-us/playready/overview/secure-delete-server#feedback)
* Content Source: [Docs/Overview/secure-delete-server.md](https://github.com/MicrosoftDocs/PlayReady/blob/live/Docs/Overview/secure-delete-server.md)
* Product: **playready**
* Technology: **drm**
* GitHub Login: @mimisasouvanh
* Microsoft Alias: **windowsdriverdev**

**Comment by swenkeratmicrosoft** [comment]
Thank you for your feedback!  If you believe the following resolution is incomplete, feel free to reactivate this issue with additional details.

The page now explicitly calls out the "record of license destruction" EME requirement.  (Searching the EME spec for "record of license destruction" will describe the requirement in detail.)

-Sam Wenker with the Microsoft PlayReady team
