### ISSUE TITLE
Compressed Digital Audio

### ISSUE THREAD

**Issue by tdaines** [MicrosoftDocs/PlayReady#54]
The table for Compressed Digital Audio OPLs seems to contradict what is found in section 3.6.2 of the Compliance Rules for PlayReady Products (March 1st, 2019).  Which is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e62b925f-084f-d997-b7a3-9ba07719194d
* Version Independent ID: 0c162551-eb4d-4572-978f-ee886ad86eec
* Content: [Output Protection Levels - PlayReady](https://docs.microsoft.com/en-us/playready/overview/output-protection-levels#feedback)
* Content Source: [Docs/Overview/output-protection-levels.md](https://github.com/MicrosoftDocs/PlayReady/blob/live/Docs/Overview/output-protection-levels.md)
* Product: **playready**
* Technology: **drm**
* GitHub Login: @mimisasouvanh
* Microsoft Alias: **windowsdriverdev**

**Comment by mwerle** [comment]
@Microsoft: We are also affected by this issue.  Could you please provide a response?

Subject to no further information, we will have to take the Compliance Rules as the definitive answer, but they have less restrictions than the linked online document.

**Comment by swenkeratmicrosoft** [comment]
Thank you for your feedback!  If you believe the following resolution is incomplete, feel free to reactivate this issue with additional details.

The page has been updated to explicitly indicate that the Compliance Rules take precedence.

-Sam Wenker with the Microsoft PlayReady team
