### ISSUE TITLE
Information provided here does not match information provided in C&R document

### ISSUE THREAD

**Issue by mwerle** [MicrosoftDocs/PlayReady#58]
The C&R (https://www.microsoft.com/playready/licensing/compliance/) section 3.6.2 on "Compressed Digital Audio Output Protection Levels" is exactly the same as section 3.6.3 for "Uncompressed Digital Audio Output Protection Levels".

However this page shows Compressed Audio as being far more restricted.

Please advise on which document is correct; also, please advise on which document(s) should take precedence in the case of further discrepancies.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e62b925f-084f-d997-b7a3-9ba07719194d
* Version Independent ID: 0c162551-eb4d-4572-978f-ee886ad86eec
* Content: [Output Protection Levels - PlayReady](https://docs.microsoft.com/en-us/playready/overview/output-protection-levels)
* Content Source: [Docs/Overview/output-protection-levels.md](https://github.com/MicrosoftDocs/PlayReady/blob/live/Docs/Overview/output-protection-levels.md)
* Product: **playready**
* Technology: **drm**
* GitHub Login: @mimisasouvanh
* Microsoft Alias: **windowsdriverdev**

**Comment by mwerle** [comment]
Eh, duplicate of #54 - I was attempting to leave feedback on the web page itself, not on GitHub!

Very poor UI, Microsoft...

**Comment by swenkeratmicrosoft** [comment]
Thank you for your feedback!  If you believe the following resolution is incomplete, feel free to reactivate this issue with additional details.

The page has been updated to explicitly indicate that the Compliance Rules take precedence.

-Sam Wenker with the Microsoft PlayReady team
