### ISSUE TITLE
这个视频无法播放呀

### ISSUE THREAD

**Issue by Raspberry-hxr** [MicrosoftDocs/PlayReady#59]
如题

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 19c5738f-9f72-33d0-898a-b87a9e5bc79d
* Version Independent ID: 4892dd22-c381-d623-0ad4-71be0b4d1721
* Content: [Packaging Content - PlayReady](https://docs.microsoft.com/zh-cn/playready/packaging/packaging-content#feedback)
* Content Source: [Docs/Packaging/packaging-content.md](https://github.com/MicrosoftDocs/PlayReady/blob/live/Docs/Packaging/packaging-content.md)
* Product: **playready**
* Technology: **drm**
* GitHub Login: @mimisasouvanh
* Microsoft Alias: **windowsdriverdev**

**Comment by swenkeratmicrosoft** [comment]
Even after translating all non-English text into English, I do not see a documentation problem, or any other problem, actually described by this issue.  As such, I am closing it.
