### ISSUE TITLE
PlayReady

### ISSUE THREAD

**Issue by tppandey** [MicrosoftDocs/PlayReady#60]
We had signedup for PlayReady.  We are not able to download the SDK with Tools in it.  Once MicroSoft was supposed to be developer friendly.  Now it seems that getting the information becoming tough.  Often times, specserver is not up running and throwing the yellow error page.  Even the freshers are handling the exceptions better.

**Comment by swenkeratmicrosoft** [comment]
If you are having difficulties obtaining the SDK, please contact wmlalicensing@microsoft.com or use the WMLA Portal as indicated on the "Support Options" page.  They should be able to quickly assist you.

Hope that helps,

-Sam Wenker with the Microsoft PlayReady team
