### ISSUE TITLE
"full sample encryption" vs "pattern encryption"

### ISSUE THREAD

**Issue by kmathewmk** [MicrosoftDocs/PlayReady#65]
What do the terms "full sample encryption" and "pattern encryption" signify? How are they dependent on the packaging format for eg HLS, DASH

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2af2d299-d877-2ec4-8173-15572fe0c2f0
* Version Independent ID: 188849b2-32fc-30ab-ce75-1c2ede2c17c7
* Content: [PlayReady Content Encryption Modes - PlayReady](https://docs.microsoft.com/en-us/playready/packaging/content-encryption-modes)
* Content Source: [Docs/Packaging/content-encryption-modes.md](https://github.com/MicrosoftDocs/PlayReady/blob/live/Docs/Packaging/content-encryption-modes.md)
* Product: **playready**
* Technology: **drm**
* GitHub Login: @mimisasouvanh
* Microsoft Alias: **windowsdriverdev**

**Comment by swenkeratmicrosoft** [comment]
Thank you for your feedback!  If you believe the following resolution is incomplete, feel free to reactivate this issue with additional details.

The Glossary and Abbreviations page (linked from PlayReady Content Encryption Modes) has been updated as follows.

Definitions for "Full Sample Encryption" and "Partial Sample Encryption" were added to link to 'cenc' and 'cbcs' respectively.
Definitions for 'cenc' and 'cbcs' were updated to link to Common Encryption (CENC).
Definition for Common Encryption (CENC) now specifies the ISO/IEC document where it is defined.  "Full Sample Encryption" and "Partial Sample Encryption" are fully defined in that specification.

-Sam Wenker with the Microsoft PlayReady team
