### ISSUE TITLE
Where can one find PlayReady Server SDK?

### ISSUE THREAD

**Issue by mc0re** [MicrosoftDocs/PlayReady#67]
The article describes it, but doesn't give a link.

**Comment by swenkeratmicrosoft** [comment]
Thank you for your feedback!  If you believe the following resolution is incomplete, feel free to reactivate this issue with additional details.

(For example, if you have specific pages in mind that you think should link to this information, reactivate.)

The "support-options.md" page now explicitly includes the following bullet under "Licensing Operations".

* Licensing and Downloading the PlayReady Device Porting Kit and the PlayReady Server SDK

-Sam Wenker with the Microsoft PlayReady team
