### ISSUE TITLE
😌

### ISSUE THREAD

**Issue by hadi93** [MicrosoftDocs/PlayReady#71]
##
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2c702f8-f74f-dfdd-c1fe-b2f26f7b871c
* Version Independent ID: 769d1677-37bf-0135-b0fb-6b5c045cb59b
* Content: [Key and Key IDs (KIDs) - PlayReady](https://docs.microsoft.com/en-us/playready/overview/key-and-key-ids-kids#feedback)
* Content Source: [Docs/Overview/key-and-key-ids-kids.md](https://github.com/MicrosoftDocs/PlayReady/blob/live/Docs/Overview/key-and-key-ids-kids.md)
* Product: **playready**
* Technology: **drm**
* GitHub Login: @mimisasouvanh
* Microsoft Alias: **windowsdriverdev**

**Comment by swenkeratmicrosoft** [comment]
This issue appears to have no content.  Closing.
